CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" (SHARD_ID VARCHAR(64), DC_NOME VARCHAR(16), CHUVA REAL, TEM_MAX REAL, TEM_MIN REAL, UMD_INS INTEGER, RAD_GLO REAL);

CREATE OR REPLACE PUMP "STREAM_PUMP" AS INSERT INTO "DESTINATION_SQL_STREAM"
    SELECT STREAM SHARD_ID, DC_NOME, CHUVA, TEM_MAX, TEM_MIN, UMD_INS, RAD_GLO
        FROM "SOURCE_SQL_STREAM_001"
